site_name: Data for Good Grenoble
site_author: Pierre-Loic Bayart
site_url: https://data-for-good-grenoble.github.io
nav:
  - ğŸŒ Bienvenue: index.md
  - ğŸ“… Ã‰vÃ¨nements: events/index.md
  - ğŸš€ Nous rejoindre: about.md

site_dir: dist
docs_dir: content

theme:
  name: material
  palette:
    primary: custom
  logo: static/icon.png
  favicon: static/favicon.png
  language: fr

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/data-for-good-grenoble/about/

    - icon: fontawesome/brands/slack
      link: https://dataforgood.fr/join

    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/fr-FR/data-for-good-fr/
